### ISSUE TITLE
Problem ordering does not persist

### ISSUE THREAD

**Issue by matthew-zhang-306** [howlbits/codescrim-bugs#12]
**This is a(n):**

- [ ] Error				
- [x] Bug				
- [ ] Feature proposal	

**Behavior:**

Previously, George implemented problem reordering on the site. It works to a degree.

Right now, the big issue is that when the problem order is set, it rarely stays that way after editing a problem in a set. For example, I can edit a problem number 2 in a set with 5 problems and when I am done, that problem will be reset to problem 5 and I will have to drag it back up again. Sometimes it gets reset to 4 instead of 5, which is also confusing.

Let me know if you need more details about this to repro it.

**Comment by geooot** [comment]
I think I completed a patch to make sure the problem order persists but haven't done that much extensive testing.
