### ISSUE TITLE
Should probably put text size limits on boxes

### ISSUE THREAD

**Issue by matthew-zhang-306** [howlbits/codescrim-bugs#16]
**This is a(n):**

- [ ] Error				
- [ ] Bug				
- [x] Feature proposal	

**Behavior:**

![image](https://user-images.githubusercontent.com/23108710/47683707-62944500-db9e-11e8-8719-160ea1324a0b.png)

See image.

EDIT: Okay so apparently having a title like this makes it so that if I go into edit view and try to change the title, it BLACKS OUT MY BROWSER.

I won't make a problem set like this ever again (AND NO ONE ELSE SHOULD) but an enforced limit would be very good.

**Comment by geooot** [comment]
lol. Fixed and should be live. However, already stored text that exceeds the limits will still break so those will need to be manually deleted for now.
